### PR TITLE
add import to resource_gcp_auth_backend.go

### PR DESCRIPTION
**Pull request by stevenaldinger**
# Adds importing for resource_gcp_auth_backend.go

The documentation suggests `terraform import vault_gcp_auth_backend.gcp gcp` should import the backend. This PR enables importing. I wasn't sure if additional tests were needed but from looking at the other auth backends it looked like this would be alright. If not, if you can point me to an existing example I'd be happy to add a test in as well.

Current behavior:
```
$-: terraform import vault_gcp_auth_backend.gcp gcp

vault_gcp_auth_backend.gcp: Importing from ID "gcp"...

Error: resource vault_gcp_auth_backend doesn't support import
```

Expected behavior (and behavior after this commit):
```
$-: terraform import vault_gcp_auth_backend.gcp gcp

vault_gcp_auth_backend.gcp: Importing from ID "gcp"...
vault_gcp_auth_backend.gcp: Import prepared!
  Prepared vault_gcp_auth_backend for import
vault_gcp_auth_backend.gcp: Refreshing state... [id=gcp]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

```release-note
* Adds support for importing GCP auth backends in "gcp_auth_backend" ([#913](https://github.com/terraform-providers/terraform-provider-vault/pull/913)).
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccXXX -timeout 120m
?   	github.com/terraform-providers/terraform-provider-vault	[no test files]
?   	github.com/terraform-providers/terraform-provider-vault/cmd/coverage	[no test files]
?   	github.com/terraform-providers/terraform-provider-vault/cmd/generate	[no test files]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-vault/codegen	(cached) [no tests to run]
?   	github.com/terraform-providers/terraform-provider-vault/generated	[no test files]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-vault/generated/datasources/transform/decode	(cached) [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-vault/generated/datasources/transform/encode	(cached) [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-vault/generated/resources/transform/alphabet	(cached) [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-vault/generated/resources/transform/role	(cached) [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-vault/generated/resources/transform/template	(cached) [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-vault/generated/resources/transform/transformation	(cached) [no tests to run]
?   	github.com/terraform-providers/terraform-provider-vault/schema	[no test files]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-vault/util	(cached) [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-vault/vault	(cached) [no tests to run]
...
```

### CODE REVIEW

**Comment by jasonodonnell** [comment]
Hi @stevenaldinger, thanks for the contribution!

This looks good but we will definitely want test coverage for the import and luckily it should be easy to add. Take a look at this test: https://github.com/terraform-providers/terraform-provider-vault/blob/master/vault/resource_ad_secret_library_test.go#L48-L75.

Let me know if you have any questions, thanks!

**Comment by jasonodonnell** [comment]
@stevenaldinger Additionally now that this repo is in the `hashicorp` org, the CLA will need to be signed. Thanks!

**Comment by stevenaldinger** [comment]
thanks for pointing me in the right direction! does this look alright with the latest commit?

```
$-: make testacc TESTARGS='-run=TestAccXXX'

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccXXX -timeout 120m
?   	github.com/terraform-providers/terraform-provider-vault	[no test files]
?   	github.com/terraform-providers/terraform-provider-vault/cmd/coverage	[no test files]
?   	github.com/terraform-providers/terraform-provider-vault/cmd/generate	[no test files]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-vault/codegen	(cached) [no tests to run]
?   	github.com/terraform-providers/terraform-provider-vault/generated	[no test files]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-vault/generated/datasources/transform/decode	(cached) [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-vault/generated/datasources/transform/encode	(cached) [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-vault/generated/resources/transform/alphabet	(cached) [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-vault/generated/resources/transform/role	(cached) [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-vault/generated/resources/transform/template	(cached) [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-vault/generated/resources/transform/transformation	(cached) [no tests to run]
?   	github.com/terraform-providers/terraform-provider-vault/schema	[no test files]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-vault/util	(cached) [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-vault/vault	0.020s [no tests to run]
```

**Comment by jasonodonnell** [comment]
@stevenaldinger Unfortunately there's still errors here, but I think I see what's going on. Here's the error:

```
    testing.go:669: Step 1 error: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.
        
        (map[string]string) {
        }
        
        
        (map[string]string) (len=3) {
         (string) (len=11) "credentials": (string) (len=683) "{\"auth_provider_x509_cert_url\":\"https://www.googleapis.com/oauth2/v1/certs\",\"auth_uri\":\"https://accounts.google.com/o/oauth2/auth\",\"client_email\":\"terraform-vault-user@terraform-vault-provider-adf134rfds.iam.gserviceaccount.com\",\"client_id\":\"123134135242342423\",\"client_x509_cert_url\":\"https://www.googleapis.com/robot/v1/metadata/x509/vault-auth-checker%40terraform-vault-provider-adf134rfds.iam.gserviceaccount.com\",\"private_key\":\"-----BEGIN PRIVATE KEY-----\\nABC123\\n-----END PRIVATE KEY-----\\n\",\"private_key_id\":\"b1e1f3cdd7fc134afsdg3547828dc2bb9dff8480\",\"project_id\":\"terraform-vault-provider-a13efc8a\",\"token_uri\":\"https://oauth2.googleapis.com/token\",\"type\":\"service_account\"}",
         (string) (len=11) "description": (string) (len=21) "gcp auth backend test",
         (string) (len=4) "path": (string) (len=3) "gcp"
        }
```

In the [read method](https://github.com/hashicorp/terraform-provider-vault/blob/master/vault/resource_gcp_auth_backend.go#L156-L179), none of these are being read/set to the resource.

Take a look at the GCP Secret Engine read method (https://github.com/hashicorp/terraform-provider-vault/blob/master/vault/resource_gcp_secret_backend.go#L134-L162), this is a good example of how it's grabbing these values and setting them. Heads up, credentials will never be returned because Vault removes that from the response for security purposes.

If you don't have the time to work this PR, I could fork it and finish, but likely won't be able to do that until early January. Let me know!

**Comment by stevenaldinger** [comment]
I'm struggling pretty hard workin on it but hate to give up. Your last comment helped a ton, I just can't run the tests locally. I feel like I changed the right spot given what you posted (adding setters to `gcpAuthBackendRead`) but the structure of the response isn't what I'm expecting (maybe) and I'm not sure how to inspect it well.

The docker-compose runs and I've got the necessary env vars set based on the Circle config but I get a "too many open files" error when I run the full suite and I get undefined function errors when I try just running the single resource_gcp_auth_backend_test.go file

**Pull request closed without merging**
