### PR TITLE
Fix external group policies getting cleared on group updates

### PR DESCRIPTION
**Pull request by lawliet89**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

This is a follow up to https://github.com/hashicorp/terraform-provider-vault/pull/1061

That PR introduced a behaviour where any update to the group will clear the entire list of policies that's managed externally on the group. Sending nothing to Vault for `policies` in an API call seems to clear all the policies on the group.  This PR proposes a change to simply read from the API and set `policies` to whatever the API returns.

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-vault/blob/master/CHANGELOG.md):

```release-note
- Fix externally managed policies on `vault_identity_group` being cleared on a group update
```

Output from acceptance testing:

```
$ VAULT_ADDR=http://127.0.0.1:8200 VAULT_TOKEN=12345 TESTARGS="--run TestAccIdentityGroup" make testacc
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test --run TestAccIdentityGroup -timeout 30m ./...
?       github.com/hashicorp/terraform-provider-vault   [no test files]
?       github.com/hashicorp/terraform-provider-vault/cmd/coverage      [no test files]
?       github.com/hashicorp/terraform-provider-vault/cmd/generate      [no test files]
ok      github.com/hashicorp/terraform-provider-vault/codegen   (cached) [no tests to run]
?       github.com/hashicorp/terraform-provider-vault/generated [no test files]
ok      github.com/hashicorp/terraform-provider-vault/generated/datasources/transform/decode    0.017s [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/generated/datasources/transform/encode    0.017s [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/generated/resources/transform/alphabet    0.019s [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/generated/resources/transform/role        0.017s [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/generated/resources/transform/template    0.018s [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/generated/resources/transform/transformation      0.017s [no tests to run]
?       github.com/hashicorp/terraform-provider-vault/helper    [no test files]
?       github.com/hashicorp/terraform-provider-vault/internal/consts   [no test files]
ok      github.com/hashicorp/terraform-provider-vault/internal/identity/entity  (cached) [no tests to run]
?       github.com/hashicorp/terraform-provider-vault/internal/identity/group   [no test files]
?       github.com/hashicorp/terraform-provider-vault/internal/identity/mfa     [no test files]
?       github.com/hashicorp/terraform-provider-vault/internal/pki      [no test files]
ok      github.com/hashicorp/terraform-provider-vault/internal/provider (cached) [no tests to run]
?       github.com/hashicorp/terraform-provider-vault/schema    [no test files]
ok      github.com/hashicorp/terraform-provider-vault/testutil  (cached) [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/util      (cached) [no tests to run]
ok      github.com/hashicorp/terraform-provider-vault/vault     24.702s
```

### CODE REVIEW

**Comment by lawliet89** [comment]
image

CLA is signed.

**Comment by lawliet89** [comment]
Fixed conflicts and test. Please can I get someone to review please.

**Comment by fairclothjm** [comment]
@lawliet89 I apologize for the delay! If you are willing to resolve the merge conflicts I am happy to review. Thanks!

**Comment by lawliet89** [comment]
@fairclothjm It has been years since I made this PR and I am not keen to do further testing. I think I've resolved the conflict correctly, but please verify.

**Comment by fairclothjm** [comment]
Thanks @lawliet89 ! Looks like this is already fixed by #2084

**Pull request closed without merging**
