### PR TITLE
chore: update vault test matrix

### PR DESCRIPTION
**Pull request by fairclothjm**

### CODE REVIEW

**Comment by fairclothjm** [comment]
Reverting the Vault SDK bump for now since it looks like we need to update TFVP. I think the failures are related to https://github.com/hashicorp/vault/pull/25744

**Comment by fairclothjm** [comment]
Also reverting the go version bump. It seems to be breaking our tests?

**Comment by vinay-gopalan** [comment]
Looks like the Secrets Sync Config test is failing due to the feature flag not being enabled. We should probably skip that test in CI since it can only be run on servers where the feature has been enabled. We can add a skip on [this line](https://github.com/hashicorp/terraform-provider-vault/blob/main/vault/resource_secrets_sync_config_test.go#L17) either in this PR or a follow up PR:

```
testutil.SkipTestEnvUnset(t, "VAULT_SECRETS_SYNC_ENABLED")
```

**Comment by fairclothjm** [comment]
@vinay-gopalan Thanks! Done in https://github.com/hashicorp/terraform-provider-vault/pull/2221/commits/48a48c9e1b31be916807308a5129a266ff2fbe1f

**Review by vinay-gopalan — APPROVED** [review]

**Pull request merged**
