### PR TITLE
fix build vault api version

### PR DESCRIPTION
**Pull request by fairclothjm**

### CODE REVIEW

**Review by tomhjp — APPROVED** [review]
I was planning to tag and import a new `api` package soon as well, but this still looks good to unblock the builds ASAP

**Comment by benashz** [comment]
@fairclothjm  It looks this broke the build on main. Might be worth taking a look at it.

**Comment by fairclothjm** [comment]
@benashz We recently added golangci-lint as a build step and that is what is failing. See https://github.com/hashicorp/terraform-provider-vault/actions/runs/8176992328/job/22357626718

 I plan to open a PR to fix the outstanding lint errors but it has been low priority recently. Sorry for the noise in the build!

**Comment by benashz** [comment]
@fairclothjm ok, we may want to disable that check then, since a failing build on main should prevent a release.

**Comment by fairclothjm** [comment]
@benashz No problem! https://github.com/hashicorp/terraform-provider-vault/pull/2179

**Pull request merged**
