### PR TITLE
add flag for all version deletion

### PR DESCRIPTION
**Pull request by Lucretius**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes https://github.com/terraform-providers/terraform-provider-vault/issues/760

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-vault/blob/master/CHANGELOG.md):

```release-note
Add `delete_all_versions` flag to `vault_generic_secret` resource to allow Terraform to delete all versions of a kv-v2 secret so that the entire secret is removed from Vault.
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

**Comment by briananstett** [comment]
@Lucretius any update on this?

**Comment by Lucretius** [comment]
> @Lucretius any update on this? 

I am pretty sure the only test that failed for this was a flaky DB related test unrelated to the added functionality so I think it just needs approval to get merged in.

**Comment by briananstett** [comment]
@kalafut would it be possible to get this merged for the next release?

**Comment by briananstett** [comment]
@catsby Any update on this? We really need this feature. We'd really would like to start using Vualt KV v2 but don't want to have oprhaned versions.

**Comment by rcreasey** [comment]
+1 for this feature

**Comment by ejtbrown** [comment]
+1 for this; would love to see it in place

**Comment by bobthebuilderberlin** [comment]
+1, we would also need this.

**Comment by vfoucault** [comment]
Adding a 👍 as well

**Pull request closed without merging**
