### PR TITLE
fix: description updates for aws_secret_backend are ignored

### LINKED ISSUE #1982: Vault provider does not update description of previously created AWS secrets engine mount
### Terraform Version
`Terraform v1.5.4`

Vault Version:
`1.14.1`

### Affected Resource(s)
- `vault_aws_secret_backend`

### Terraform Configuration Files
```hcl
resource "vault_aws_secret_backend" "group-aws-mount" {
  path                      = "group-aws"
  description               = "AWS Engine mount for group"
  default_lease_ttl_seconds = 600
  max_lease_ttl_seconds     = 600
}
```

### Debug Output
- `TODO` Will update later when I have a chance

### Expected Behavior
`Terraform should have updated the description to the correct text for the AWS secrets engine.  Initial creation of the resource works as expected.`

### Actual Behavior
`The descriptions stayed the same even though the apply says it completed successfully.  The vault UI itself showed no change and the next terraform plan showed a plan to change still that should have happened during the previous apply.`

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
`It is important to note that using the vault CLI the description updated successfully thus the terraform provider itself seems to be the issue`

### References
`None I could find`

### PR DESCRIPTION
**Pull request by jgrumboe**
### Description

This PR fixes the `vault_aws_secret_backend` that updates of `description` are written to Vault.

Closes #1982 

### Checklist
- [x] Added [CHANGELOG](https://github.com/hashicorp/terraform-provider-vault/blob/master/CHANGELOG.md) entry (only for user-facing changes)
- [x] Acceptance tests where run against all supported Vault Versions

### Output from acceptance testing:

```
❯ make testacc TESTARGS='-run=AWSSecretBackend -v'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test -run=AWSSecretBackend -v -timeout 30m ./...
?       github.com/hashicorp/terraform-provider-vault   [no test files]
?       github.com/hashicorp/terraform-provider-vault/cmd/coverage      [no test files]
?       github.com/hashicorp/terraform-provider-vault/cmd/generate      [no test files]
?       github.com/hashicorp/terraform-provider-vault/generated [no test files]
testing: warning: no tests to run
PASS
ok      github.com/hashicorp/terraform-provider-vault/codegen   (cached) [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/hashicorp/terraform-provider-vault/generated/datasources/transform/decode    (cached) [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/hashicorp/terraform-provider-vault/generated/datasources/transform/encode    (cached) [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/hashicorp/terraform-provider-vault/generated/resources/transform/alphabet    (cached) [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/hashicorp/terraform-provider-vault/generated/resources/transform/role        (cached) [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/hashicorp/terraform-provider-vault/generated/resources/transform/template    (cached) [no tests to run]
?       github.com/hashicorp/terraform-provider-vault/helper    [no test files]
?       github.com/hashicorp/terraform-provider-vault/internal/consts   [no test files]
?       github.com/hashicorp/terraform-provider-vault/internal/identity/group   [no test files]
?       github.com/hashicorp/terraform-provider-vault/internal/identity/mfa     [no test files]
?       github.com/hashicorp/terraform-provider-vault/internal/pki      [no test files]
?       github.com/hashicorp/terraform-provider-vault/schema    [no test files]
testing: warning: no tests to run
PASS
ok      github.com/hashicorp/terraform-provider-vault/generated/resources/transform/transformation      (cached) [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/hashicorp/terraform-provider-vault/internal/identity/entity  (cached) [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/hashicorp/terraform-provider-vault/internal/provider (cached) [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/hashicorp/terraform-provider-vault/testutil  (cached) [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/hashicorp/terraform-provider-vault/util      (cached) [no tests to run]
2023/10/18 00:05:32 [INFO] Using Vault token with the following policies: root
=== RUN   TestAccAWSSecretBackendRole_basic
--- PASS: TestAccAWSSecretBackendRole_basic (5.62s)
=== RUN   TestAccAWSSecretBackendRole_import
--- PASS: TestAccAWSSecretBackendRole_import (4.98s)
=== RUN   TestAccAWSSecretBackendRole_nested
--- PASS: TestAccAWSSecretBackendRole_nested (3.82s)
=== RUN   TestAccAWSSecretBackendStaticRole
    resource_aws_secret_backend_static_role_test.go:21: "AWS_STATIC_USER" must be set
--- SKIP: TestAccAWSSecretBackendStaticRole (0.00s)
=== RUN   TestAccAWSSecretBackend_basic
--- PASS: TestAccAWSSecretBackend_basic (5.23s)
=== RUN   TestAccAWSSecretBackend_usernameTempl
--- PASS: TestAccAWSSecretBackend_usernameTempl (2.35s)
=== RUN   TestAccAWSSecretBackend_remount
--- PASS: TestAccAWSSecretBackend_remount (4.80s)
PASS
ok      github.com/hashicorp/terraform-provider-vault/vault     27.448s
```

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

### CODE REVIEW

**Comment by jgrumboe** [comment]
It would be nice to get the `hacktoberfest-accepted` label on this PR, if it's ok. Thanks

**Comment by jgrumboe** [comment]
@fairclothjm I just found out that `vault_jwt_auth_backend` is also failing to update `description`, maybe others too.
Should I include it in this PR or open a new one?

**Comment by fairclothjm** [comment]
@jgrumboe I haven't had a chance to look at this closely. But if you do open a PR for jwt auth please do so in a separate PR. I recall the the handling of `description` is not consistent across different backend resources. I think this has to do with the description needing to be a part of the `tune` configuration in vault but not all resources make use of `tune`. Again, I haven't looked closely at this but that is what I recall.

**Comment by jgrumboe** [comment]
I will open a separate PR for other description issues.

**Comment by jgrumboe** [comment]
Can this PR be merged?

**Comment by jgrumboe** [comment]
Is anything missing for merging?

**Review by fairclothjm — APPROVED** [review]
LGTM! Thanks @jgrumboe !

**Pull request merged**
